[General]
bypass-system = true
private-ip-answer = true
always-ip-address = true
tun-excluded-routes = 127.0.0.1,*.lan,*.local,*.backloop.dev
dns-server = https://dns.sgvrz.net/dns-query,https://d.adguard-dns.com/dns-query/ba91a56b
update-url = https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/base.conf


[Rule]
RULE-SET,https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/rule/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/rule/proxy.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/rule/reject.list,REJECT