[General]
update-url = https://raw.githubusercontent.com/sgvrz-svc/shadowrocket/main/base.conf

[Rule]
RULE-SET,https://raw.githubusercontent.com/sgvrz-svc/shadowrocket/main/rule/reject.list,REJECT