[General]
bypass-system = true
dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = false
dns-server = https://dns.sgvrz.net/query/sgu
fallback-dns-server = https://dns.sgvrz.net/query/sgu
update-url = https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/base.conf

[Rule]
RULE-SET,https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/list/reject.list,REJECT