[General]
include = base.conf
bypass-system = true
private-ip-answer = true
always-ip-address = true
tun-excluded-routes = 127.0.0.1,*.backloop.dev
dns-server = https://d.adguard-dns.com/dns-query/ba91a56b
update-url = https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/default.conf

[Rule]
FINAL, DIRECT