[General]
include = base.conf
fallback-dns-server = 89.124.109.19,77.88.8.8
update-url = https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/mobile.conf

[Rule]
RULE-SET,https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/rule/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/rule/proxy.list,PROXY
FINAL,PROXY