[General]
include = base.conf
update-url = https://raw.githubusercontent.com/sgvrz-svc/repo/main/shadowrocket/mobile.conf

[Rule]
DOMAIN-WILDCARD, imap.*, PROXY
DOMAIN-WILDCARD, *metric*, REJECT
DOMAIN-WILDCARD, *analytic*, REJECT
DOMAIN-WILDCARD, *firebase*, REJECT
DOMAIN-WILDCARD, *facebook*, REJECT
DOMAIN-WILDCARD, *crashlytics*, REJECT
DOMAIN-WILDCARD, *appsflyersdk*, REJECT
DOMAIN-WILDCARD, *app*adjust*, REJECT
DOMAIN-WILDCARD, *startup*mobile*, REJECT
DOMAIN-WILDCARD, *firebaseinstallations*, REJECT
DOMAIN-WILDCARD, logly.*, REJECT
DOMAIN-WILDCARD, siri.apple.*, REJECT
DOMAIN-WILDCARD, experiments.apple.*, REJECT
DOMAIN-WILDCARD, auth.2gis.*, PROXY
DOMAIN-WILDCARD, maps.2gis.*, PROXY
DOMAIN-WILDCARD, reviews.2gis.*, PROXY
DOMAIN-WILDCARD, jam.api.2gis.*, PROXY
DOMAIN-WILDCARD, hybrid.api.2gis.*, PROXY
DOMAIN-WILDCARD, options.api.2gis.*, PROXY
DOMAIN-WILDCARD, transport.api.2gis.*, PROXY
DOMAIN-WILDCARD, *.2gis.*, REJECT
DOMAIN-WILDCARD, *social*t*bank*, REJECT
DOMAIN-WILDCARD, *hotels*t*bank*, REJECT
DOMAIN-WILDCARD, *stories*t*bank*, REJECT
DOMAIN-WILDCARD, *shopping*t*bank*, REJECT
DOMAIN-WILDCARD, maps.starline.ru, REJECT
FINAL,PROXY