[General]
include = base.conf
bypass-system = true
private-ip-answer = true
always-ip-address = true
tun-excluded-routes = 127.0.0.1,*.backloop.dev
fallback-dns-server = 77.88.8.8
dns-server = https://d.adguard-dns.com/dns-query/ba91a56b
update-url = https://raw.githubusercontent.com/sgvrz-svc/shadowrocket/main/mobile.conf

[Rule]
RULE-SET,https://raw.githubusercontent.com/sgvrz-svc/shadowrocket/main/rule/direct.list,DIRECT
FINAL,PROXY